// Printer Component
//
// IBM 1131 Console Printer simulator with:
// - Greenbar paper display
// - 15.5 CPS Selectric typewriter effect
// - Sampled audio for authentic sound
// - Auto-scroll

use yew::prelude::*;
use gloo::timers::callback::Timeout;
use wasm_bindgen::prelude::*;

/// Printer state
#[derive(Clone, PartialEq)]
#[derive(Default)]
pub struct PrinterState {
    /// Lines that have been fully printed
    pub completed_lines: Vec<String>,
    /// Current line being printed
    pub current_line: String,
    /// Current character position in the line being printed
    pub char_position: usize,
    /// Whether printing is active
    pub printing: bool,
    /// Queue of lines to print
    pub queue: Vec<String>,
}


#[derive(Properties, PartialEq)]
pub struct PrinterProps {
    /// Lines to print
    #[prop_or_default]
    pub content: Vec<String>,
    /// Whether to auto-start printing
    #[prop_or(false)]
    pub auto_start: bool,
    /// Callback when printing completes
    #[prop_or_default]
    pub on_complete: Callback<()>,
    /// Sound enabled
    #[prop_or(true)]
    pub sound_enabled: bool,
}

#[function_component(Printer)]
pub fn printer(props: &PrinterProps) -> Html {
    let state = use_state(PrinterState::default);
    let printing_active = use_state(|| false);
    let audio_initialized = use_state(|| false);

    // Initialize audio on first interaction
    let init_audio = {
        let audio_initialized = audio_initialized.clone();
        Callback::from(move |_: MouseEvent| {
            if !*audio_initialized {
                init_web_audio();
                audio_initialized.set(true);
            }
        })
    };

    // Start printing handler
    let start_printing = {
        let state = state.clone();
        let printing_active = printing_active.clone();
        let audio_initialized = audio_initialized.clone();
        let content = props.content.clone();
        Callback::from(move |_: MouseEvent| {
            if !*audio_initialized {
                init_web_audio();
                audio_initialized.set(true);
            }

            let mut new_state = (*state).clone();
            new_state.queue = content.clone();
            new_state.printing = true;
            state.set(new_state);
            printing_active.set(true);
        })
    };

    // Printing loop effect
    {
        let state = state.clone();
        let printing_active = printing_active.clone();
        let on_complete = props.on_complete.clone();
        let sound_enabled = props.sound_enabled;

        use_effect_with((*printing_active, (*state).clone()), move |(active, current_state)| {
            let timeout: Option<Timeout> = if *active {
                let state = state.clone();
                let printing_active = printing_active.clone();
                let on_complete = on_complete.clone();
                let current_state = current_state.clone();

                // Calculate delay (base 65ms for 15.5 CPS)
                let base_delay = 65u32;
                let delay = if current_state.char_position == 0 && !current_state.current_line.is_empty() {
                    base_delay + 30 // Line start delay
                } else {
                    base_delay + (js_sys::Math::random() * 15.0) as u32
                };

                Some(Timeout::new(delay, move || {
                    let mut new_state = current_state.clone();

                    // If we have a current line being printed
                    if !new_state.current_line.is_empty() {
                        if new_state.char_position < new_state.current_line.len() {
                            // Print next character
                            let ch = new_state.current_line.chars().nth(new_state.char_position);
                            if let Some(c) = ch
                                && sound_enabled {
                                    // Only play sounds for actual printed characters, not every space
                                    if c == ' ' {
                                        // Only play space sound occasionally (every ~5 spaces)
                                        if new_state.char_position % 5 == 0 {
                                            play_space_sound();
                                        }
                                    } else {
                                        play_click_sound(c);
                                    }
                                }
                            new_state.char_position += 1;
                            state.set(new_state);
                        } else {
                            // Line complete, add to completed lines
                            if sound_enabled {
                                play_line_feed_sound();
                            }
                            new_state.completed_lines.push(new_state.current_line.clone());
                            new_state.current_line = String::new();
                            new_state.char_position = 0;
                            state.set(new_state);
                        }
                    } else if !new_state.queue.is_empty() {
                        // Start next line from queue - trim trailing whitespace for faster printing
                        let line = new_state.queue.remove(0);
                        new_state.current_line = line.trim_end().to_string();
                        new_state.char_position = 0;
                        state.set(new_state);
                    } else {
                        // Printing complete
                        new_state.printing = false;
                        state.set(new_state);
                        printing_active.set(false);
                        on_complete.emit(());
                    }
                }))
            } else {
                None
            };

            // Keep timeout alive
            move || drop(timeout)
        });
    }

    // Get the partial line being printed
    let partial_line: String = if state.char_position > 0 {
        state.current_line.chars().take(state.char_position).collect()
    } else {
        String::new()
    };

    // Auto-scroll to bottom when content changes (paper feeds up)
    {
        let line_count = state.completed_lines.len();
        use_effect_with(line_count, move |_| {
            // Scroll greenbar to bottom to show newest content
            if let Some(window) = web_sys::window()
                && let Some(document) = window.document()
                    && let Some(element) = document.get_element_by_id("greenbar") {
                        let scroll_height = element.scroll_height();
                        element.set_scroll_top(scroll_height);
                    }
            || ()
        });
    }

    html! {
        <div class="printer" onclick={init_audio}>
            <div class="printer-header">
                <h2 class="printer-title">{"IBM 1053 Console Printer"}</h2>
                <div class="printer-info">
                    <span class="paper-info">{"13\" Paper"}</span>
                    <span class="char-info">{"130 Char/Line"}</span>
                    <span class="cps-info">{"15.5 CPS Selectric"}</span>
                </div>
            </div>

            <div class="paper-container">
                <div class="greenbar" id="greenbar">
                    <div class="spacer"></div>
                    <div class="output">
                        // Completed lines
                        { for state.completed_lines.iter().map(|line| {
                            html! { <div class="line">{line}</div> }
                        })}
                        // Current line being typed
                        if !partial_line.is_empty() {
                            <div class="line current">{&partial_line}<span class="cursor">{"_"}</span></div>
                        }
                    </div>
                </div>
            </div>

            <div class="printer-controls">
                <button
                    class="start-button"
                    onclick={start_printing}
                    disabled={*printing_active || props.content.is_empty()}
                >
                    {if *printing_active { "PRINTING..." } else { "START PRINT" }}
                </button>
                <span class="line-count">
                    {format!("Lines: {}", state.completed_lines.len())}
                </span>
            </div>
        </div>
    }
}

/// Sample assembler listing for demo
/// IBM 1053 Console Printer: 13" paper, 130 characters per line
pub fn sample_assembler_listing() -> Vec<String> {
    vec![
        "// JOB    T".to_string(),
        "// ASM".to_string(),
        "*LIST".to_string(),
        "*NAME SAMPLE".to_string(),
        "".to_string(),
        "                              IBM 1130 ASSEMBLER                              PAGE    1".to_string(),
        "".to_string(),
        " STMT   ADDR   OBJECT     LABEL    OP    OPERANDS                        COMMENTS".to_string(),
        "".to_string(),
        "    1                               * SAMPLE IBM 1130 PROGRAM - COUNTER LOOP".to_string(),
        "    2                               * DEMONSTRATES ARITHMETIC AND BRANCHING".to_string(),
        "    3                               * WRITTEN FOR IBM 1130 WITH 1053 CONSOLE".to_string(),
        "    4                               *".to_string(),
        "    5   0100            START       EQU   /100                   PROGRAM ORIGIN".to_string(),
        "    6   0100   C108                 LD    COUNT                  LOAD COUNTER".to_string(),
        "    7   0101   8109                 A     ONE                    ADD ONE".to_string(),
        "    8   0102   D108                 STO   COUNT                  STORE RESULT".to_string(),
        "    9   0103   C108                 LD    COUNT                  RELOAD FOR COMPARE".to_string(),
        "   10   0104   110A                 S     LIMIT                  SUBTRACT LIMIT".to_string(),
        "   11   0105   4C20                 BSC   L     DONE,+-          BRANCH IF >= LIMIT".to_string(),
        "   12   0106   7000                 MDX         0                NO-OP (LOOP)".to_string(),
        "   13   0107   4C00                 BSC   L     START            BRANCH TO START".to_string(),
        "   14   0108   0000     COUNT       DC    0                      COUNTER STORAGE".to_string(),
        "   15   0109   0001     ONE         DC    1                      CONSTANT ONE".to_string(),
        "   16   010A   000A     LIMIT       DC    10                     LOOP LIMIT".to_string(),
        "   17   010B   0000     DONE        DC    0                      END MARKER".to_string(),
        "   18                               END   START                  ENTRY AT START".to_string(),
        "".to_string(),
        "                                    SYMBOL TABLE".to_string(),
        "".to_string(),
        "  SYMBOL    VALUE     SYMBOL    VALUE     SYMBOL    VALUE".to_string(),
        "  COUNT     0108      DONE      010B      LIMIT     010A".to_string(),
        "  ONE       0109      START     0100".to_string(),
        "".to_string(),
        "  ASSEMBLY COMPLETE - NO ERRORS DETECTED           CORE USED: 000C WORDS".to_string(),
        "".to_string(),
        "// XEQ".to_string(),
    ]
}

// Web Audio functions (called via wasm-bindgen)
#[wasm_bindgen]
extern "C" {
    #[wasm_bindgen(js_namespace = console)]
    fn log(s: &str);
}

// Embedded typewriter click sound (base64-encoded WAV)
const CLICK_AUDIO_B64: &str = "UklGRl4eAABXQVZFZm10ICgAAAD+/wEAgLsAAAB3AQACABAAFgAQAAEAAAABAAAAAAAQAIAAAKoAOJtxTElTVBoAAABJTkZPSVNGVA0AAABMYXZmNjIuMy4xMDAAAGRhdGEAHgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAP////8AAAAAAAAAAAAAAAAAAAAAAQABAAAAAAAAAAEAAQABAAEAAAAAAAAAAQACAAIAAQAAAAEAAwACAAEAAgABAAIAAgABAAMAAgABAAMAAwACAAIAAgACAAEAAgABAAEAAQAAAAIAAQAAAAEAAQABAAIAAQABAAEAAAABAAIAAQACAAIAAQABAAIAAgABAAEAAAAAAAIAAgABAAIAAQABAAEAAQABAAAAAQABAAEAAQACAAIAAQACAAIAAgACAAEAAAABAAMAAgACAAIAAgADAAMAAwACAAEAAwAEAAMAAwADAAIAAwADAAIAAgACAAAAAgADAAMAAwADAAMABAAEAAQAAgACAAQABQAEAAMAAwADAAMAAwAEAAQAAgADAAQAAwAEAAQAAgADAAMAAwACAAIABAAEAAMAAgADAAQAAwAEAAQABAADAAEABAADAAIAAgACAAMAAwADAAMAAgACAAEAAAADAAIAAgACAAEAAQABAAIAAgACAAEAAAACAAIAAgACAAEAAgACAAIAAwABAAEABAADAAIAAgABAAMAAQACAAIAAAABAAIAAgACAAIAAQADAAMAAgADAAEAAQADAAQAAwABAAIAAgACAAIAAgADAAIAAgADAAIAAgACAAIAAQABAAIAAwACAAIABAADAAMAAwADAAMAAwAEAAMAAgABAAIABAADAAIAAwACAAMABAADAAIAAgACAAQABAAEAAMAAwADAAQABAADAAEAAgAEAAMAAwACAAMABAACAAIAAwADAAIAAgADAAIAAQACAAMAAgACAAMAAgACAAAAAgACAAIAAgABAAIAAQACAAQAAgABAAIAAgABAAIAAQABAAEAAQACAAEAAwABAP//AAD//wEAAAAAAAEAAQAAAAAAAQAAAAAAAgABAAEAAQABAAEAAQABAAEAAQAAAAEAAgABAAEAAQAAAAEAAgABAAAAAAACAAEAAQABAAAAAQABAAEAAAD//wAAAAAAAAAA//8AAAAAAAD//wAAAAD/////AAAAAAAAAAD//wAAAAAAAAAA/v/+/wAAAAD/////AAAAAP//AAAAAP7/AAD+//7/AAD//wAAAAD////////////////8//7/AAD+/wAA/v////////8AAP/////+////AAD+////AAD//wAAAAAAAAAA/v///wAA/v8AAP7///8AAP//AAD//////v/9////AAAAAP//////////AAD/////AAAAAP//AAABAAAAAAABAAAAAAD/////AQAAAAAAAQD//wEAAQABAAEA//8BAAIAAAABAAIAAQAAAAAAAgAAAP//AQACAAEAAQAAAAAAAAAAAQAAAAIAAQAAAAIAAQAAAAAAAAAAAP//AQACAAAAAQACAAIAAQACAAEAAQABAAEAAQABAAEAAQACAAEAAQABAAIAAQABAAIAAgACAAAAAAACAAEAAQABAAEAAQABAAIAAgACAAAAAAACAAEAAQABAAIAAQADAAMAAgADAAEAAwADAAIAAgACAAQAAgADAAMAAwACAAEABAAEAAMAAwACAAMAAgADAAMAAwACAAMAAwACAAMAAwADAAMAAwACAAIAAQACAAQAAwADAAIAAQACAAIAAgABAAIAAwABAAIAAwACAAIAAwACAAIAAgACAAMAAQABAAIAAAABAAIAAQABAAIAAQABAAEA//8AAAEAAQABAAEAAgAAAAIAAQABAAEA//8AAAEAAAAAAAAAAAAAAP//AQAAAP//AAAAAAAAAAABAAEAAQABAAAAAQD//wAAAQAAAAAAAAAAAAAAAQAAAAAAAAD+/wAAAQAAAAAA//8AAAAAAAAAAAAA//8AAAEAAQABAAEAAAABAAAAAAAAAP////8AAAEAAQAAAAAAAAAAAAEAAQAAAP//AAAAAAEAAAAAAAEAAAAAAAEAAAD/////AAAAAP//AAAAAAAAAAABAAEAAQAAAP//AAAAAAAAAAAAAAAAAAABAAEAAAD//wAAAQABAAEAAQAAAAEAAQABAAAAAAABAAEAAQABAAEAAQABAAEAAgAAAAEAAQABAAEAAAABAAEAAAABAAEAAAAAAP////8AAAEAAQABAAEAAAAAAAEAAgAAAAAAAQABAAEAAQABAAEAAAABAAEAAQD//wAAAgABAAAAAAABAAEAAAAAAAEAAQAAAAEAAgABAAEAAQABAAEAAQABAAAAAAABAAEAAAAAAAAAAAD//wAAAAD//wAA//8AAAAAAAAAAP//AAAAAAAAAAAAAP7/AAAAAP//AAD//wAA//////////8AAP///////wAA////////////////AAD///7/AAAAAAAAAAAAAP//AAD////////9////AAD//////v////////////3//v///////v/+///////+/////////wAA/f/+/////////////v/+/wAA//////7//f////7//v/////////////////+//3/AAAAAP//AAD//wAAAAD//wAA////////AQAAAAAA/////wAAAAAAAP///v/+///////+//7//f/+//3//v/+//7////9//7//////////////////v/+/////f/9/wAA/v/+//7//v/+/////////////v8AAAAA////////AAD/////AAAAAP7/AAAAAP//AAD//wEA//8BAP7//v8BAPX/+v////3////+/wEAAQACAP//AQD///r/AwD///7//f/6//z/+f/8//f/+//6//P/+//6//v/+//6//r/+v/6//r//v/1//b////+//z/+//+//7//P/8/wAAAAD8//j/+/8EAP7/AAD///3/AwD//wEA/v8AAPz/9v8FAAAA/v8AAP/////9/wMA/P/5/wIAAgABAAMAAgAAAAIAAQADAAIAAwACAPn/AQAFAAIABgAEAAQAAwADAAYAAgAEAAcA+//9/wUA/v8AAAEA/P8AAAEAAgACAAEA/f/4//7/AgD9//7//f/7//3/+//+//f/9P8AAAAA//8AAP3//v////3///////z////5//v/AQD6//v/+//3//j//f////v/9f/3/////P/+//7//P/9//z/AQAAAAEA";

// Embedded spacebar click sound (base64-encoded WAV)
const SPACE_AUDIO_B64: &str = "UklGRl4tAABXQVZFZm10ICgAAAD+/wEAgLsAAAB3AQACABAAFgAQAAEAAAABAAAAAAAQAIAAAKoAOJtxTElTVBoAAABJTkZPSVNGVA0AAABMYXZmNjIuMy4xMDAAAGRhdGEALQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////////v/+//7////+///////+/////v/+//////////////8AAAAA/v/+/////v////7//v////7//v/+////AQD///7//////////v////7///8AAP7//v////7////+///////+/////v///////f/+//7//v/+//7//v/+//3//v////3//f/9//3//f/9//7//f/9//7///////3//f/+//3//f/+//7//v/+//7//////wAA///+///////+//7///////7//v///wAA//////7///////7///////////////////////7//////wAA/////////v/+//7/AAAAAP7//v/+////AAD///////////////8AAAAA/v///wAAAAAAAP//////////AAABAAAAAAAAAP//////////AAAAAP//AQABAP//AAAAAP//AAAAAAAAAAAAAAAAAAABAAAA/////wAAAAAAAAAAAAD//wAAAAABAAAA//8AAAAAAAAAAAAAAAAAAAEAAAABAAAA//8AAAAAAQAAAAAAAAAAAAAAAAABAAEA/////wEAAQABAAAAAQABAAAAAgABAAAAAAABAAEAAQABAAEAAQACAAEAAgACAAEAAQABAAEAAQACAAEAAQABAAIAAQABAAEAAgABAAAAAQABAAEAAQAAAAIAAgABAAAAAQABAAEAAQABAAEAAAACAAEAAgABAAEAAQAAAAAAAQAAAAAAAAABAAAAAAABAAAAAAABAP//AAAAAAAAAQAAAAEAAgABAAAAAAAAAAEAAAABAAEAAAAAAAAAAQACAAAAAAD//wAAAQABAAEAAAABAAIAAgAAAAAAAQAAAAEAAQAAAAAAAAAAAAIAAgAAAAAAAQABAAAAAAABAAAAAAAAAAAAAgABAAAAAAAAAAEAAAAAAAAAAAABAAAAAQAAAAAAAAAAAAEAAAAAAAEAAQABAAIAAgAAAAAAAAAAAAAA//8AAP//AAAAAAAAAQD//wAA/////wAA//8AAAAA//8AAAEA/////wAA/////////////wAA//8BAAEA//8AAP//AAAAAAAAAAD///////8AAP//////////AAD//wAAAAD///////8BAP////8AAP//AAAAAP////8AAAAA//8AAAAA//8AAP////8AAP////8AAP7///8AAP7//v/+//7//v/9//7//v/+//3//v/9//z////+//7//v/+//7//f/9//3/AAD+//3//v/9//3//f////7//v/9//7/AAD9//3//f/+//7//f/+//3//v/+//7//v/9//7//f/+//7//v/+//7//f///////f/9//3///////3//v/9//7//v/+/////v/+//7////+//3//v/9//7////+//3//v/+//3//v/+//7//v/+/wAA///9//7////+//7//f/+//7//v////7//f/+//7//v/+//3//f/9//7//v///////f/+//7//v/+/////v/+/////v///////v////7////+/////v/+/wAA/v///wAA//////////////////////////8AAP///v/////////////////+/////////////v8AAP7///////7/AAAAAP////8AAP////8AAP//AAAAAP///////wAAAAD//////////wAAAAD//wAA//8AAAEAAAD///////8AAP//AAAAAP//AAD/////AQD//wAAAAAAAAAA/////////////wAAAAD+/wAAAAAAAAAAAAD/////AAAAAP///////////////////////////v8AAP////8AAP///v///wAA////////AAABAP7///////////8AAAEA//8AAP//AAABAP//AAAAAAAAAAD/////AAAAAAAAAAD/////AAD///////8AAAAAAQABAAEAAgAAAAAAAAABAAEAAQABAAEAAAABAAIAAgAAAAEAAAABAAAAAAAAAAAAAQAAAAEAAgAAAAAAAQAAAAEAAQABAAEAAQAAAAEAAgAAAAAAAAAAAAEAAAABAAEAAQADAAAAAQACAAEAAQABAAEAAQABAAEAAgAAAAAAAQABAAAAAAAAAAEAAAAAAAAAAAACAAEA//8AAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAP//AAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAD//wAAAAAAAP//AAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAD//wAAAAAAAAAAAAAAAAAA//8AAAAAAAAAAAAAAAAAAAAAAQAAAP//AAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAAD/////AAAAAAAAAAABAAAAAAACAAEAAQABAAAAAQABAAEAAQAAAAMAAgABAAIAAQACAAMAAgABAAEAAgACAAEAAgACAAAAAAABAAAAAAAAAAEAAAAAAAEAAgACAAEAAQABAAEAAQAAAAEAAQABAAEAAgADAAIAAAABAAAAAAAAAAAAAAD//wEAAQD//wAAAAD//////////wAAAAD//wEAAAD+///////+//7//v/9//7//f/+/////f/9//7//v/+//3//v/9//3//v///////v/////////+//7///8AAP//AQABAP///////wAAAAAAAAAA//8CAAAABwAIAAEAAwADAAcABgABAAQABAAGAAMADQAKAAQACAADAAcACAAFAAYACAAGAAUADgAFAAEABgAGAAYABAADAAEAAwAAAAUACQD+////AAACAAAA/f/9//7//v8CAAYA+//9////+//6//j//P/4//v/+P/7//7/9P/4//T/9v/2//b/9//z//v/9f/6//v/8v/0//X/+P/2//b/8//z//b/9//8//f/9//3//b/9//1//j/9//3//j////+//X/+P/5//n/+f/5//v/+//6//7/BgD7//j//P/4//z/+v/6//z/+v/8//7//v/5//r/+v/6//r/+P/6//n/+v/5//3//v/4//z/+v////7/+v/+//v//P/6/wEAAQD5//z/+v////z/+//+//3//f/7/wYAAgD8//z//v8AAP3/AAD+/wAA/v8CAAgA//8BAAEAAwAEAAUABQAGAAgACgAOAAYAAwAFAAQABQADAAUAAQAAAAAABgAHAP//AwAAAAEAAQACAAMA//8BAAAACQAIAAMABAAEAAYABQACAAAABQD+/wEABgD5//v/+//4//n//P/8//j//f/+/wMAAwD//wEAAQAEAAUAAwADAAUAAgADAAkAAwABAAUACAAHAAcABgAIAAkABgANAAsABAALAA0ADQAQABAADgAQAA4AEwAYAA4ADgARAA8AEgAUABQAFAATABQAHAAcABUAFQAXABgAFQAYABcAFgAUABMAHAAXABUAFgAUABQAFAAZABYAGAAYAB0AIgAXABgAGQAWABUAEQAOAAkACgAPAAkABAALAA0ACwAPAA4ADgAMAAkABQAEAAIA9f/0//H/7f/u/+3/8f/w//n/+/8BAAgAAgALABAAEwAUABYAGgAXABsAGwAdABsAFgAaABoAGgAbABoAHAAeAB0AJAAfABgAHgAZABgAFwAWABQAEQAUABEAFwAZABIAEgAVABsAGQAYABwAIwAjACUAKQAjACEAIQAhACAAIQAfAB0AGwATABkAGAAPAAoACAAEAP/////6//v/9v/0//3/9v/0//b/9P/1//P/8v/0//f/+v8DAAIAAwAFAAkAEwAQABUAFgAWABoAHwAfABIAEwAUABIAEwASABMADAAQABIAEAAWABAADgAUABQAEwASABYAFwAYABkAHAAgABgAEgAPAAkABwADAP3//P/9//3//P/5//z/BAAAAAQABgAHAAsABgAOABAABgACAAMAAwACAAIAAwAEAAQABQACAAYABgAAAAgABQAEAAYABQAIAAcADAAPAAYAAgAHAAUAAgAGAAgACgAIAAkABgAMABEABAAEAAEA+//5//j/9//0//j/8v/5//r/8P/x/+//8f/t/+v/7P/q/+r/5v/r/+f/4f/j/+P/5f/m/+T/5f/s/+b/5//t/+n/6f/j/+j/6//m/+z/6v/s//f/+v/4//7/BAADAAcACgAMAAsACwALABAAEwAIAAkACwAJAAoADAAPAA0ADgAPABIAGQARAAoADgAIAAQABwAAAAAAAQD+/wQA///8/wIAAwAEAAQABwAJAAgADAAOAAYAAwABAAEAAQAAAP//+//9//3/AgADAP3////7//n/9//5//j/8//0//P/+//7//f/9//2//v/+P/2//r//f/+/wEABQAAAAMABwAKAAYAAQAEAAEAAgD8//z/AAD1//b/+f/5//3//v///wIABgAIAA4ADQAHAAoACwALAAwADAALAAsADwAMABIAFAAMAA8AEAAPABEAFAASAA8AFAAVAB0AIgAaABgAGwAhACEAHQAfACIAIQAiACIAGwAbABsAGAAUAA0ADgARABEAEAATAA8ABgAJAAcABwAFAAEAAgABAAEAAQADAPr/9v/5//X/9P/y//T/9P/u/+X/4v/o/+r/8/8DABcAEgD6/+j/5v8GACUANQAvABgAAADl/+H/9v8OABkAHQAgABgAFQAnAD4AQgA+ADkAPABKAFQAWQBLADsAHgABAAQAFwA3AEEAKAAFAPD//v8bABkA4P/P/wEAQABpAHQAaQBCACQAJgBPAHsAbgBGAC4ANQBAADcAGQDo/7L/h/+T/8T/8P8AAOv/3P/o/wUAMgBZAFEALQASAAoADgAIAAAA9v/f/7//pv+Z/6H/sf+i/6b/0P8BAB4AGwAUAA4ADgAXADQAOwAQAOf/yv/L/+3/GgA4ACkAAADd/8z/xf/U/+//BAAkAEAATABDADQAHwD3//H/AgAJABMAEgAFAPz/CAAqAD0ALQD4/8n/uf+j/5j/sf/i/w0AJQAyAEEAVABgAFkALgDx/7r/k/+b/8D/5f8AAAQA+//r/9n/xv/T//L/6//W/87/0v/n//H/7f/s/+7/6P/W/8b/vf+6/73/w//K/9P/4v/n/+f/+v8OABQACwD7//j/AgAJABoAMwAvACcALwAyACUACgDz//X/BwAQABYAJwAiAAsA+P/s//L/AAANABIADAARACAALgA4AC4AGAAbACwALwApACMAJAAcAAIA6v/j/9//0v/I/8T/zv/n/+X/zf+6/7j/1f/5/xEAHwARAO//2P/G/7D/qf+1/7X/rv+2/9D///8jACcAGQDz/8H/n/+D/2//gf+0/+f/EwApABoADQARAAsAAwAGAAoAHwA+AEoARQAkAOf/vv+s/5b/lP+//wsAaQC7ANsA3ADHAIEAMwDv/7L/oP+2/9H/4//+/yUAPgA+ACUACgDy/9r/0//N/9X/9f8FAP7//P////L/1f+2/6T/rv/C/9v//P8YADMASgBGABoA5P++/6b/qP+6/9b//f8XACEAKQAzABwA5//A/7f/zf/9/zsAbgCAAHUAVgAmAPH/zv/H/9D/7P8gAFYAdwCDAHEAOQD6/8j/sP/B/+f/BAAXADIATgBlAGgAOAD8/9r/2P/v//z/8//l/+X/7v/+/xIACADy/+D/vv+d/5f/uP/U/9b/2//h/9j/vP+r/5n/ef9+/6f/zP/l//z/AADb/8X/2P/7/xsAJAAkAC0AOwBCAEQATwBNADEACwDx//v/DAASAA4A9//c/8f/v//M/97/zv+g/4f/gP99/5r/xv/l/wgAMQBJAFQAVwBAABMA8P/r/wEAHQA1AEEALQANAPr/6P/X/9D/3f8FAEcAfwCMAIMAagBEACYACADy//D/BwAgAB4AFQAOAAgABwAFAPr/5P/h//D/AgASABkAHwAZAAoABwADAAMADwAjACoAGAD7/9b/vP+n/5z/s//X/+3/3f+z/4j/Yf9R/1j/bv+B/5P/r//A/73/sP+f/4r/dv9y/2r/Zf9t/3P/ef95/3b/cv9w/3P/cv92/4H/mf/C/+r/BwANAAYA/v/x/+P/4P/n/93/z//j/wMAFgAcABUAAQDw/+r/5//3/wgAEgAhABoADwARAA4AEQApAEkAcgCdAK8ArQCwAKoApACjAJUAfgBnAFAAQgBJAFAAQgApABcAHgApAB8AFQASABQAKQBCAEYAOQAxAC0AKQAsACwAKQAsADAAMgA2AC8AJgAsAC4AJgAXAPr/4P/P/8j/zv/Q/8D/rv+h/5n/lf+K/3H/Wv9Y/2f/gP+c/63/rf+e/4r/ff9u/2L/Z/91/4//rv+3/7D/qP+Y/4L/bf9c/1H/UP9f/3T/hP+N/4P/dv9o/0//Pf8w/yD/I/83/1L/aP9q/2j/bP9s/3f/kP+m/73/1v/t/wEACgACAPn/8f/d/8v/yv/S/+r/BgATACQANgAyACYAHQAUABwALAA7AEoAWABlAGwAaQBmAGcAbQB3AIUAlwCkAK8AuwC5AK0AoACTAJAAjgCKAI4AjACEAH8AcwBkAGAAXQBcAGEAZwBsAHIAdwB2AHgAdABkAFoAVwBXAFwAXgBXAE4ARgBGAEYAPQA5ADYALwApACQAHwAdAB4AJgApACIAGwAZABgAFAAKAP3/8f/r/+7/8f/x//H/8v/x/+r/4//i/+P/5//r/+//9//5//L/8v/1//T/9v/7//v/+P/7//3/BAAXACQAIQAZABUAFgAcACMAKwAwADQAQABJAEIAOwA9AD0ANgAzADUANwA9AEoAVABaAGMAbgB1AIAAjACUAJsAoACdAJUAkACNAIkAggB5AHYAcgBuAG8AcwB8AIcAkQCfAK4AsQCrAKYAowCfAJwAmQCVAI0AhACIAJAAjQCIAIoAigCMAJMAmgCgAKIAnQCbAJoAjAB+AHsAdwB0AHQAcwB0AHoAfQCAAIEAeQBpAFkARgA3AC8ALQAsACYAGgAPAAkAAQDz/+f/2v/L/77/tP+k/47/f/91/2r/ZP9g/13/XP9c/17/Y/9j/17/Yv9p/2v/bP9u/3L/e/9//37/ff93/3T/eP96/3j/df9u/2n/cP93/37/jP+T/5P/m/+o/7X/wP/H/8z/0f/S/9j/6f/0//f/+v/7//r/+v/3//H/6//f/9L/yf+//7X/sf+v/6j/ov+f/57/nP+Z/5j/k/+L/4n/jv+R/4v/hf+D/4H/f/+E/4b/e/9w/23/cP94/4D/gf+F/4n/if+N/5T/kP+K/4r/i/+L/4j/g/9//3f/bf9q/2n/Yv9d/17/Yf9k/2f/av9v/3H/dP96/37/gv+J/5D/k/+U/5n/o/+o/6n/sv+8/7T/rP+x/7X/vP/L/9D/yf/C/73/v//F/8P/vP+5/7r/wv/N/9T/1P/Q/8j/yP/M/8z/zf/Q/9L/0f/Q/8//0f/V/9L/y//F/8f/zf/Q/9L/0f/R/9P/0P/I/8v/1f/Z/97/6f/u/+//8f/y//L/8P/p/+n/7v/s/+v/8f/2//j/+v///wYAEAAZACUANQA4ADMANQBDAE8AVgBcAF0AWABcAGsAdgB8AIMAiQCQAJoAoAClAKQAmgCSAJAAigCGAIYAfQBzAHAAcABxAHYAeAB3AHYAdQB2AHkAfQB/AHwAeQB4AHMAbgBsAGUAWQBSAE4ASwBGAD4AOAA1ACsAJQAoACQAFwAQAAoAAAD6//b/9f/1//T/8v/y/+z/5v/q//P/+v/+////AAAFAAsAFAAeAB8AHQAfAB4AGQAXABkAGAAUABIAFgAYABMADwATABUAEgAQABAAEgAWABoAFwAQABIAGAAXABMAFAAVABUAEgAQABMAFAAOAAgACgAOABMAFgAWABYAFgAaACMAJwAkACUAKQAqAC8ANgA7AEEARwBPAFsAZQBnAGgAaABlAGQAZQBmAGYAaQBuAG8AagBoAG0AbgBtAG0AbQBpAGgAawBtAGgAYABeAF8AXgBeAFkATgBGADoALgAqACgAIAAdABwAFgAQAAwABwADAP3/+f/9//7/+P/6////+v/0//D/6//p/+z/8f/2//T/8P/w/+//6//q/+7/9P///wkADQASAB4AJwArAC0ALQAqACoAMgA6AEIARgBCADwAPQBBAEMARAA/ADcAMgAvADEANQAxACQAHAAXAA8ABwADAP3/9f/w/+7/5//h/+L/4v/d/9j/1v/S/8v/";

fn init_web_audio() {
    // Initialize audio context and decode embedded samples
    let _ = js_sys::eval(&format!(r#"
        (async function() {{
            if (!window.printerAudioCtx) {{
                window.printerAudioCtx = new (window.AudioContext || window.webkitAudioContext)();
            }}

            // Helper to decode base64 to ArrayBuffer
            function base64ToArrayBuffer(base64) {{
                const binaryString = atob(base64);
                const bytes = new Uint8Array(binaryString.length);
                for (let i = 0; i < binaryString.length; i++) {{
                    bytes[i] = binaryString.charCodeAt(i);
                }}
                return bytes.buffer.slice(0);
            }}

            // Decode click sound if not already done
            if (!window.printerClickBuffer) {{
                try {{
                    const arrayBuffer = base64ToArrayBuffer("{click_b64}");
                    window.printerClickBuffer = await window.printerAudioCtx.decodeAudioData(arrayBuffer);
                }} catch (e) {{
                    console.warn("Failed to decode click audio:", e);
                }}
            }}

            // Decode space sound if not already done
            if (!window.printerSpaceBuffer) {{
                try {{
                    const arrayBuffer = base64ToArrayBuffer("{space_b64}");
                    window.printerSpaceBuffer = await window.printerAudioCtx.decodeAudioData(arrayBuffer);
                }} catch (e) {{
                    console.warn("Failed to decode space audio:", e);
                }}
            }}
        }})();
    "#, click_b64 = CLICK_AUDIO_B64, space_b64 = SPACE_AUDIO_B64));
}

fn play_click_sound(char: char) {
    // Play sampled typewriter click with pitch variation based on character
    let char_code = char as u32;
    let playback_rate = 0.9 + (char_code % 20) as f64 * 0.01;

    let _ = js_sys::eval(&format!(r#"
        if (window.printerAudioCtx && window.printerClickBuffer) {{
            const source = window.printerAudioCtx.createBufferSource();
            const gain = window.printerAudioCtx.createGain();

            source.buffer = window.printerClickBuffer;
            source.playbackRate.value = {rate};

            gain.gain.value = 0.6;

            source.connect(gain);
            gain.connect(window.printerAudioCtx.destination);

            source.start();
        }}
    "#, rate = playback_rate));
}

fn play_space_sound() {
    // Play sampled spacebar click
    let _ = js_sys::eval(r#"
        if (window.printerAudioCtx && window.printerSpaceBuffer) {
            const source = window.printerAudioCtx.createBufferSource();
            const gain = window.printerAudioCtx.createGain();

            source.buffer = window.printerSpaceBuffer;
            source.playbackRate.value = 1.0;

            gain.gain.value = 1.2;

            source.connect(gain);
            gain.connect(window.printerAudioCtx.destination);

            source.start();
        }
    "#);
}

fn play_line_feed_sound() {
    // Synthesized whir sound for platen roll (same as standalone demo)
    let _ = js_sys::eval(r#"
        if (window.printerAudioCtx) {
            const osc = window.printerAudioCtx.createOscillator();
            const gain = window.printerAudioCtx.createGain();

            osc.frequency.value = 300;
            osc.frequency.linearRampToValueAtTime(200, window.printerAudioCtx.currentTime + 0.05);
            osc.type = 'sawtooth';

            gain.gain.value = 0.08;
            gain.gain.exponentialRampToValueAtTime(0.001, window.printerAudioCtx.currentTime + 0.05);

            osc.connect(gain);
            gain.connect(window.printerAudioCtx.destination);

            osc.start();
            osc.stop(window.printerAudioCtx.currentTime + 0.05);
        }
    "#);
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_printer_state_default() {
        let state = PrinterState::default();
        assert!(state.completed_lines.is_empty());
        assert!(state.current_line.is_empty());
        assert_eq!(state.char_position, 0);
        assert!(!state.printing);
    }

    #[test]
    fn test_sample_listing() {
        let listing = sample_assembler_listing();
        assert!(!listing.is_empty());
        assert!(listing[0].contains("JOB"));
    }
}
